
version: 2

models:
    - name: curr_entity_bals
      description: "A table storing total current on-chain balances aggregated on (entity, network, asset)"
      # columns:
      #     - name: id
      #       description: "The primary key for this table"
      #       tests:
      #           - unique
      #           - not_null