version: 2

models:
  - name: flipside

    # Document within the same codebase
    description: My Flipside query written in Python

    # Configure in ways that feel intuitive and familiar
    config:
      # packages:
      #   - pandas
      #   - shroomdk
      #   - json
      #   - pathlib
      materialized: table
      tags: ['python']

    # # Test the results of my Python transformation
    # columns:
    #   - name: id
    #     # Standard validation for 'grain' of Python results
    #     tests:
    #       - unique
    #       - not_null
    # tests:
    #   # Write your own validation logic (in SQL) for Python results
    #   - [custom_generic_test](writing-custom-generic-tests)